### ISSUE TITLE
Theme broke after the last update

### ISSUE THREAD

**Issue by Ryukomat44** [PatrykBielanin/discord-cyberpunk2077-theme#10]
Had to open this issue again cause after the yesterday update, some parts of the theme revert back to the default color.
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/79204745/99293316-b24a-4c34-a5d3-ac8c089def66)

**Comment by PatrykBielanin** [comment]
I will drop update this evening, closing because one issue about it is already open 😊 #9

**Comment by Ryukomat44** [comment]
@PatrykBielanin ok thanks.😊
