### ISSUE TITLE
New discord update seems to break the theme

### ISSUE THREAD

**Issue by Pashetas** [PatrykBielanin/discord-cyberpunk2077-theme#11]
After the recent update, the server side bar,  message tab and the panel with your username, deafen, mute and settings buttons are not appearing the same color as everything else.

**Comment by JuniorLoch** [comment]
can confirm, dont know if other themes break too though or if its only this one

**Comment by IamDocBray** [comment]
Sadly same issue here. It's like 75% of it is working still but the Discord update looks to have changed what CSS needs to be used for some things. Hopefully this theme can be updated to account for it, this is my hands down favorite theme to use :D

Very much miss the bigger blocks for denoting categories of channels in a server

![Discord_30March2024-11-11-23](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/165492670/1fbc00b0-e725-40ca-a3c3-4a345eb8a146)

**Comment by Emtyloc** [comment]
I fixed most of the problems or the main ones I found.
[cyberpunk2077.theme.base.zip](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14858464/cyberpunk2077.theme.base.zip)
the main problems were the CSS classes I made some kind of mapping if u guys are interested.
[cyberpunk_css_fix.txt](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14858494/cyberpunk_css_fix.txt)

**Comment by Emtyloc** [comment]
> I fixed most of the problems or the main ones I found. [cyberpunk2077.theme.base.zip](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14858464/cyberpunk2077.theme.base.zip) the main problems were the CSS classes I made some kind of mapping if u guys are interested. [cyberpunk_css_fix.txt](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14858494/cyberpunk_css_fix.txt)

Many classes still need to be replaced, but for the moment I don't have much time to spend.

**Comment by IamDocBray** [comment]
No worries on the time frame, I know how it can go. I might be able to test this out later after work. Thank you for the awesome theme and the WIP updates! 

You are greatly apprecaited.

**Comment by Emtyloc** [comment]
[cyberpunk2077.theme.base.zip](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14879339/cyberpunk2077.theme.base.zip)
[cyberpunk_css_fix.txt](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14879343/cyberpunk_css_fix.txt)

![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/88388684/2afa8d25-2803-4934-9a38-34bf76ac9feb)
new fix.

note: need to put both files in the theme folder, then on Vencord themes select cyberpunk2077, not the base one.

**Comment by IamDocBray** [comment]
Working like a charm on Vencord, gracias!

**Comment by IgiariValkyr** [comment]
> [cyberpunk2077.theme.base.zip](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14879339/cyberpunk2077.theme.base.zip) [cyberpunk_css_fix.txt](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/files/14879343/cyberpunk_css_fix.txt)
> 
> ![image](https://private-user-images.githubusercontent.com/88388684/319845193-7899f99f-9a81-4b89-b670-4460888df939.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTc2NDAsIm5iZiI6MTcxMjcxNzM0MCwicGF0aCI6Ii84ODM4ODY4NC8zMTk4NDUxOTMtNzg5OWY5OWYtOWE4MS00Yjg5LWI2NzAtNDQ2MDg4OGRmOTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMTVmMWQ5ZDRhMDlmMzBlMTAzZGUyNjMyYTQ5NTJkZDg5M2E5ZjllNjY4MjljMDk4YzIyMzgyODA4ZGQ2YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQ9tYnGbW4q3gCtJEYCezJr0pIwkaUP0nyHvqwjTCt8)
> 
> new fix.
> 
> note: need to put both files in the theme folder, then on Vencord themes select cyberpunk2077, not the base one.

Got a version for Better Discord?

**Comment by Emtyloc** [comment]
sry guys, I do not have a testing environment for better discord, but all you need to know to fix the theme is CSS, then inspect the app using the Chrome inspector shortcut, then replace the CSS classes for the correct ones in the theme CSS, here is an example of how it should look like.
The main parts of the APP are commented on in the base.css downloaded from the main branch.
You can test your changes in real time using the quick CSS, located in settings.
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/88388684/b3d87959-4882-47b9-8a66-e8960d1682c9)

**Comment by klovnious** [comment]
Hmm, this a bit out of my reach unfortunately.
@PatrykBielanin are you aware of the issue and is there a ETA on possible fix for this?

**Comment by PatrykBielanin** [comment]
Sorry guys for keeping you waiting for so long. I spend almost two weeks in hospital due to some health problems, i wasn't even able to check my emails or discord DM's. I read all of your comments, huge thank you to @Emtyloc for fixing most of the problems in my theme. Today's evening or tomorrow i will merge your changes to the main branch and also fix others issues. It's nice to see that i can rely on some of you to when it comes to fixing this theme 😎❤️
