### ISSUE TITLE
Another discord update broke the theme

### ISSUE THREAD

**Issue by Sizzuns** [PatrykBielanin/discord-cyberpunk2077-theme#15]
After yesterday's update, the theme broke down again, making many elements gray and not matching the rest

**Comment by Pashetas** [comment]
Yep, can confirm the same happenend to me too. Its same as last time it happened.

**Comment by Tupraa** [comment]
Same issue here

**Comment by Maicouh** [comment]
Same

**Comment by Omega172** [comment]
Fixed in my PR https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/pull/16

**Comment by GukeyGuke** [comment]
> Fixed in my PR #16

You are a hero.

**Comment by haydnthehurst** [comment]
> Fixed in my PR #16

You're awesome, thank you!

**Comment by jigglesworthbinglebob** [comment]
> Fixed in my PR #16

that does seem to have fixed the majority of it, although the headings for "text channels" and  "voice channels" and their associated dropdown menu seem to be the wrong color (i'm using the provided screenshots as reference). any fix or is it my own user error?

**Comment by Sizzuns** [comment]
> Fixed in my PR #16

Awesome, thank you

**Comment by Sizzuns** [comment]
> > Fixed in my PR #16
> 
> that does seem to have fixed the majority of it, although the headings for "text channels" and "voice channels" and their associated dropdown menu seem to be the wrong color (i'm using the provided screenshots as reference). any fix or is it my own user error?

this should help:
`.defaultColor_e9e35f{
  color: var(--neon-blue-color) !important;
}`

**Comment by Sizzuns** [comment]
> > Fixed in my PR #16
> 
> that does seem to have fixed the majority of it, although the headings for "text channels" and "voice channels" and their associated dropdown menu seem to be the wrong color (i'm using the provided screenshots as reference). any fix or is it my own user error?

This should help
`.defaultColor_e9e35f{
  color: var(--neon-blue-color) !important;
}`

**Comment by jigglesworthbinglebob** [comment]
> > > Fixed in my PR #16
> > 
> > 
> > that does seem to have fixed the majority of it, although the headings for "text channels" and "voice channels" and their associated dropdown menu seem to be the wrong color (i'm using the provided screenshots as reference). any fix or is it my own user error?
> 
> This should help `.defaultColor_e9e35f{ color: var(--neon-blue-color) !important; }`

where should I put this line in? i took a look at both css files and didn't see a line it would replace but maybe i missed it.

**Comment by Sizzuns** [comment]
> > > > Fixed in my PR #16
> > > 
> > > 
> > > that does seem to have fixed the majority of it, although the headings for "text channels" and "voice channels" and their associated dropdown menu seem to be the wrong color (i'm using the provided screenshots as reference). any fix or is it my own user error?
> > 
> > 
> > This should help `.defaultColor_e9e35f{ color: var(--neon-blue-color) !important; }`
> 
> where should I put this line in? i took a look at both css files and didn't see a line it would replace but maybe i missed it.

Open discord settings then go to themes, and click the "pen icon" next to your theme. The editor window will pop up. Scroll to the bottom and paste it in new line.

**Comment by Silent-legent** [comment]
> Fixed in my PR #16

can u explain how to fix the css? duno undertans anything of this stuf :)

**Comment by Silent-legent** [comment]
> Fixed in my PR #16

is there a way that u can fix this;
if u go to like chats with friends etc, the logo in the corner has yellow around it
also if i look at ss in better discord the logo should be red but it isnt

**Comment by Sizzuns** [comment]
> > Fixed in my PR #16
> 
> is there a way that u can fix this; if u go to like chats with friends etc, the logo in the corner has yellow around it also if i look at ss in better discord the logo should be red but it isnt
Try this
probably not how it should be styled, but it works

`.childWrapper_f90abb{
  color: var(--neon-red-color) !important;
}
.childWrapper_f90abb:hover, .childWrapper_f90abb
.warpper_f90abb.selected_f090abb .childWrapper_f90abb {
 background-color: var(--neon-yellow-color) !important;
}

.tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 {
  background-color: var(--neon-yellow-color) !important;
  border-radius:1rem;
  
}`

**Comment by Sizzuns** [comment]
``

> > Fixed in my PR #16
> 
> is there a way that u can fix this; if u go to like chats with friends etc, the logo in the corner has yellow around it also if i look at ss in better discord the logo should be red but it isnt

Try this.
probably not how it should be styled, but it works

`.childWrapper_f90abb{
  color: var(--neon-red-color) !important;
}
.childWrapper_f90abb:hover, .childWrapper_f90abb
.warpper_f90abb.selected_f090abb .childWrapper_f90abb {
 background-color: var(--neon-yellow-color) !important;
}

.tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 {
  background-color: var(--neon-yellow-color) !important;
  border-radius:1rem;
  
}`

**Comment by Silent-legent** [comment]
> .childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> 
> .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> 
> }

just put in new line?

**Comment by Silent-legent** [comment]
> > > Fixed in my PR #16
> > 
> > 
> > is there a way that u can fix this; if u go to like chats with friends etc, the logo in the corner has yellow around it also if i look at ss in better discord the logo should be red but it isnt
> 
> Try this. probably not how it should be styled, but it works
> 
> `.childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> 
> .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> 
> }`

![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/174837411/a17d58b7-709f-4325-a073-37585ac64b21)
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/174837411/c2853b2b-efa0-4491-87cf-395424cca9f5)

**Comment by Sizzuns** [comment]
looking at the screen from website
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/56275373/b47b6765-e334-40aa-92f0-92e6bbdf5079)
it looks the same

**Comment by Sizzuns** [comment]
> > > > Fixed in my PR #16
> > > 
> > > 
> > > is there a way that u can fix this; if u go to like chats with friends etc, the logo in the corner has yellow around it also if i look at ss in better discord the logo should be red but it isnt
> > 
> > 
> > Try this. probably not how it should be styled, but it works
> > `.childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> > .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> > }`
> 
> ![image](https://private-user-images.githubusercontent.com/174837411/346296951-a17d58b7-709f-4325-a073-37585ac64b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc3MzksIm5iZiI6MTcyMDI5NzQzOSwicGF0aCI6Ii8xNzQ4Mzc0MTEvMzQ2Mjk2OTUxLWExN2Q1OGI3LTcwOWYtNDMyNS1hMDczLTM3NTg1YWM2NGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQyMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDQwMDlhMDkwNjRjYjZiNTkzOWM4NTAwYzFhNDcwMDdhYTk0N2MyOTFiMzZmYmQ0YWFkYTIyOWI4ZGUxOTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4agMOh8xMAj46zZH_cQhlljRz2ZExvRxxRJo5j2CVY) ![image](https://private-user-images.githubusercontent.com/174837411/346296955-c2853b2b-efa0-4491-87cf-395424cca9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc3MzksIm5iZiI6MTcyMDI5NzQzOSwicGF0aCI6Ii8xNzQ4Mzc0MTEvMzQ2Mjk2OTU1LWMyODUzYjJiLWVmYTAtNDQ5MS04N2NmLTM5NTQyNGNjYTlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQyMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjM4ZjBjZWM1OTFlMjFkZmMwMDA4NjI5YjU3MDg0MDhiZDkxMzgwMWNkNjkyOWY3ZTc5OTc1YzIzNjM5YjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WPr71Iw43bq4VgLPSLT13hM9AYTm8DfKz-6-wltzQY0)

looking at the screen from website
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/56275373/b47b6765-e334-40aa-92f0-92e6bbdf5079)
it looks the same

**Comment by Silent-legent** [comment]
> > > > > Fixed in my PR #16
> > > > 
> > > > 
> > > > is there a way that u can fix this; if u go to like chats with friends etc, the logo in the corner has yellow around it also if i look at ss in better discord the logo should be red but it isnt
> > > 
> > > 
> > > Try this. probably not how it should be styled, but it works
> > > `.childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; } .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem; }`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/174837411/346296951-a17d58b7-709f-4325-a073-37585ac64b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc3MzksIm5iZiI6MTcyMDI5NzQzOSwicGF0aCI6Ii8xNzQ4Mzc0MTEvMzQ2Mjk2OTUxLWExN2Q1OGI3LTcwOWYtNDMyNS1hMDczLTM3NTg1YWM2NGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQyMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDQwMDlhMDkwNjRjYjZiNTkzOWM4NTAwYzFhNDcwMDdhYTk0N2MyOTFiMzZmYmQ0YWFkYTIyOWI4ZGUxOTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4agMOh8xMAj46zZH_cQhlljRz2ZExvRxxRJo5j2CVY) ![image](https://private-user-images.githubusercontent.com/174837411/346296955-c2853b2b-efa0-4491-87cf-395424cca9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc3MzksIm5iZiI6MTcyMDI5NzQzOSwicGF0aCI6Ii8xNzQ4Mzc0MTEvMzQ2Mjk2OTU1LWMyODUzYjJiLWVmYTAtNDQ5MS04N2NmLTM5NTQyNGNjYTlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQyMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjM4ZjBjZWM1OTFlMjFkZmMwMDA4NjI5YjU3MDg0MDhiZDkxMzgwMWNkNjkyOWY3ZTc5OTc1YzIzNjM5YjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WPr71Iw43bq4VgLPSLT13hM9AYTm8DfKz-6-wltzQY0)
> 
> looking at the screen from website ![image](https://private-user-images.githubusercontent.com/56275373/346296986-b47b6765-e334-40aa-92f0-92e6bbdf5079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc4NDAsIm5iZiI6MTcyMDI5NzU0MCwicGF0aCI6Ii81NjI3NTM3My8zNDYyOTY5ODYtYjQ3YjY3NjUtZTMzNC00MGFhLTkyZjAtOTJlNmJiZGY1MDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDIwMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjFmOThkY2QyNjcwNTU2M2ViOGI4ZGNiMGYwMzE0NmI1ZThiZjRmOTZlOGQ5ODlkNDNiY2M2YTRiODkwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZPT7_hXK4ZBIW5He3166_maglh6bErLompMJraVuoWE) it looks the same

ik, idk how it sould look if u in a dm but beside that being blue it works it's better than having a yellow box around it

**Comment by Sizzuns** [comment]
i tried to make it look like i remebered (when you are in dm page). I suck at css but somehow i managed to repaired it, so i'm glad you like it

**Comment by Sizzuns** [comment]
for me it looks like this 
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/56275373/11ec9f65-dba4-4823-8db3-4f3a0653cf80)

**Comment by Sizzuns** [comment]
> > for me it looks like this ![image](https://private-user-images.githubusercontent.com/56275373/346297266-11ec9f65-dba4-4823-8db3-4f3a0653cf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTgyMjAsIm5iZiI6MTcyMDI5NzkyMCwicGF0aCI6Ii81NjI3NTM3My8zNDYyOTcyNjYtMTFlYzlmNjUtZGJhNC00ODIzLThkYjMtNGYzYTA2NTNjZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDIwMzIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YWY0Y2U3NDRhNmM0ZDYyOWUyNjA0OGM0ZWYwNDk2ZTVhOTA3ODIxYWRiMjM4YjAzN2FlNDk5NTgzYjkzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9t32xZmTxCfalT9ECmgvDUx959_1-6OjyNhe0QRNt-8)
> 
> u on app or website?

app

**Comment by Silent-legent** [comment]
> > > for me it looks like this ![image](https://private-user-images.githubusercontent.com/56275373/346297266-11ec9f65-dba4-4823-8db3-4f3a0653cf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTgyMjAsIm5iZiI6MTcyMDI5NzkyMCwicGF0aCI6Ii81NjI3NTM3My8zNDYyOTcyNjYtMTFlYzlmNjUtZGJhNC00ODIzLThkYjMtNGYzYTA2NTNjZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDIwMzIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YWY0Y2U3NDRhNmM0ZDYyOWUyNjA0OGM0ZWYwNDk2ZTVhOTA3ODIxYWRiMjM4YjAzN2FlNDk5NTgzYjkzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9t32xZmTxCfalT9ECmgvDUx959_1-6OjyNhe0QRNt-8)
> > 
> > 
> > u on app or website?
> 
> app

maybe thats the isue, i cant check atm (or its a vencord isue)
or i did sum wrong with pasting it in idk

**Comment by Silent-legent** [comment]
> .childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> 
> .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> 
> }

if i hover over it, it is fully yellow only its blue when om not (with lil yellow around the notif amount)

**Comment by Sizzuns** [comment]
I see that when I refreshed the discord it looks like yours. Like I said, I suck at css so I apologize that not everything works, I will try to fix it and if I can get it to work as expected. 

sorry for my English ;x

**Comment by Silent-legent** [comment]
> .childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> 
> .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> 
> }

dw  bro :), u alr did a great job with coloring the logo, if u get it to work il prob see it late af, since i dont rll use github

**Comment by Sizzuns** [comment]
![image](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/56275373/e88f2034-8c92-4c45-97ba-99059e4e9ca9)
It looks like this now 


`/*MY FIX - CHANNEL TITLE AT THE TOP CENTER OF THE SCREEN*/
.defaultColor_e9e35f{
  color: var(--neon-blue-color) !important;
}

/*DISCORD LOGO FIX*/
.childWrapper_f90abb{
  color: var(--neon-red-color) !important;
  
}
.childWrapper_f90abb:hover, .childWrapper_f90abb
.warpper_f90abb.selected_f090abb .childWrapper_f90abb,
.childWrapperNoHoverBg_f90abb {
 background-color: var(--neon-yellow-color) !important;
}

.tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 {
  background-color: var(--neon-yellow-color) !important;
  border-radius:1rem;
  
}`

**Comment by Sizzuns** [comment]
> > .childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> > .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> > }
> 
> dw bro :), u alr did a great job with coloring the logo, if u get it to work il prob see it late af, since i dont rll use github
> 
> EDIT; if i have it corect the yellow part is there but for sum reason the blue is just over it (prob a isue with the hover state of the icon (or thats what gpt tries to removeif i give code to him(he aint rll helping tbh))

yeah i missed ".childWrapperNoHoverBg_f90abb" but i send a fixed code above

**Comment by Silent-legent** [comment]
> > > .childWrapper_f90abb{ color: var(--neon-red-color) !important; } .childWrapper_f90abb:hover, .childWrapper_f90abb .warpper_f90abb.selected_f090abb .childWrapper_f90abb { background-color: var(--neon-yellow-color) !important; }
> > > .tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 { background-color: var(--neon-yellow-color) !important; border-radius:1rem;
> > > }
> > 
> > 
> > dw bro :), u alr did a great job with coloring the logo, if u get it to work il prob see it late af, since i dont rll use github
> > EDIT; if i have it corect the yellow part is there but for sum reason the blue is just over it (prob a isue with the hover state of the icon (or thats what gpt tries to removeif i give code to him(he aint rll helping tbh))
> 
> yeah i missed ".childWrapperNoHoverBg_f90abb" but i send a fixed code above

now we have the isue of the yelow around the logo when u not in a dm;
this sould work 'if u can make it better idm (this what gpt gave me'

"/* Base logo color */
.childWrapper_f90abb {
    color: var(--neon-red-color) !important;
    background-color: transparent !important; /* No background when not in DM */
}

/* Background color when hovering or selected in general */
.childWrapper_f90abb:hover, 
.warpper_f90abb.selected_f090abb .childWrapper_f90abb {
    background-color: var(--neon-yellow-color) !important;
}

/* Handle the tutorial and list items */
.tutorialContainer_f9623d .selected_dfb2f8, 
.listItemWrapper_dfb2f8 .selected_dfb2f8 {
    background-color: var(--neon-yellow-color) !important;
    border-radius: 1rem;
}

/* Additional specific rules for DM context */
.childWrapper_f90abb.selected_f090abb, 
.childWrapper_f90abb.dm_selected {
    background-color: var(--neon-yellow-color) !important;
}

/* Ensure no background color when not in DM */
:not(.selected_f090abb):not(.dm_selected) .childWrapper_f90abb {
    background-color: transparent !important;
}"

**Comment by Silent-legent** [comment]
i dont rll know, if u hover over the icon without u being in a dm, did it get the yellow around it or not?

**Comment by Sizzuns** [comment]
what about now?

```
/*MY FIX - CHANNEL TITLE AT THE TOP CENTER OF THE SCREEN*/
.defaultColor_e9e35f{
  color: var(--neon-blue-color) !important;
}

/*DISCORD LOGO FIX*/
.childWrapper_f90abb{
  color: var(--neon-red-color) !important;
  
}
.childWrapper_f90abb:hover, .childWrapper_f90abb
.warpper_f90abb.selected_f090abb .childWrapper_f90abb,
.childWrapperNoHoverBg_f90abb {
 background-color: var(--neon-yellow-color) !important;
}

.tutorialContainer_f9623d .selected_dfb2f8, .listItemWrapper_dfb2f8 .selected_dfb2f8 {
  background-color: transparent !important;
  border-radius:1rem;
  
}
```

**Comment by Silent-legent** [comment]
didnt fix for me

**Comment by Sizzuns** [comment]
it's hard for me to try something else, because everything works for me :/

**Comment by Silent-legent** [comment]
> it's hard for me to try something else, because everything works for me :/

yh, but i gave a lil code above that works for me

**Comment by Silent-legent** [comment]
> it's hard for me to try something else, because everything works for me :/

but thank you for ur help, couldnt have got a it fixed without 👍 :)

**Comment by GukeyGuke** [comment]
Square avatars seem to not be working once again, anyone know a fix ? Would be very appreciated :)

**Comment by Silent-legent** [comment]
> Square avatars seem to not be working once again, anyone know a fix ? Would be very appreciated :)

square avatars?

**Comment by GukeyGuke** [comment]
> > Square avatars seem to not be working once again, anyone know a fix ? Would be very appreciated :)
> 
> square avatars?

User avatars in chat, when Omega created his PR it worked for a bit but its back to circle avatars now, the blue tint seems to be also gone from replies. 
![image](https://github.com/user-attachments/assets/d2b1bae0-d9a3-4334-9287-44e1f7a41fac)

**Comment by Seeenchous** [comment]
Hey guys, I have a problem like this - can you help me please?
![Снимок экрана (368)](https://github.com/user-attachments/assets/ccd00076-11e1-4588-820b-854769196bd8)

**Comment by Seeenchous** [comment]
Hey guys! I have this problem, with grey elements - can you help me, please?
![изображение_2024-07-28_205459080](https://github.com/user-attachments/assets/bcbf13a0-6ab7-4cde-93b7-ca887a85cc8c)

**Comment by IgiariValkyr** [comment]
Yep. It seems that _**once again**_ another discord update has broken the theme.

**Comment by InsaneGal** [comment]
When's it getting fixed?

**Comment by Omega172** [comment]
Small fixes for some of the stuff that was broken that i wanted back PR https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/pull/16

**Comment by SDMatthe** [comment]
Noob here, how do I use the version from the PR instead of the main branch?

**Comment by PatrykBielanin** [comment]
Thank you very much for your work @Omega172  and for keeping this theme updated with your contribution while i completety couldn't engage in development. I merged yours change into main branch. 😎
