### ISSUE TITLE
[BUG] Forum page having incorrect colors and the top bar having a gray outline too

### ISSUE THREAD

**Issue by Maicouh** [PatrykBielanin/discord-cyberpunk2077-theme#19]
![Näyttökuva 2024-10-14 201745](https://github.com/user-attachments/assets/8a5839ad-e780-4cee-b508-d08edb27bc24)
![Näyttökuva 2024-10-14 202621](https://github.com/user-attachments/assets/5e04b75d-0848-4613-a84d-b368dd44e588)

**Comment by PatrykBielanin** [comment]
Fixed with #20
