### ISSUE TITLE
Line is off

### ISSUE THREAD

**Issue by Eric-Sparda** [PatrykBielanin/discord-cyberpunk2077-theme#7]
line in the left box and in chat box are not on the same line

![Capture](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/36969229/4d8e3f34-2d2b-4297-9b5a-aaee2a97a65f)

**Comment by PatrykBielanin** [comment]
Problem fixed in latest update.

**Comment by Eric-Sparda** [comment]
amazing job!
