### ISSUE TITLE
Theme breaks after updating discord

### ISSUE THREAD

**Issue by Ryukomat44** [PatrykBielanin/discord-cyberpunk2077-theme#8]
![IMG_20231017_215120](https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/79204745/6ebf27a4-da3a-4cfd-91db-d9a90dc1e7fa)
The profile section, the connected voice chat, the typing bar and the "person is typing ..." revert back to default colors after updating discord. both on better discord and vencord. reinstalling the theme didn't help either.

**Comment by TomBonnot** [comment]
+1 just saw that lately

**Comment by PatrykBielanin** [comment]
Im gonna take a look and fix it asap. Probably im gonna drop update this evening 👌I will leave a comment when its fixed.

**Comment by Ryukomat44** [comment]
@PatrykBielanin Thanks for the rapid response.😊

**Comment by PatrykBielanin** [comment]
I just dropped new update with fixes. Thank you for letting me know. Your theme should update itself in next 12h 😎

**Comment by TomBonnot** [comment]
@PatrykBielanin much fast, such great, much thanks ! It’s resolved !

**Comment by Ryukomat44** [comment]
@PatrykBielanin Excellent support! many thanks.
